### ISSUE TITLE
how to make zfs-fuse support acl

### ISSUE THREAD

**Issue by lihui2090** [sehe/zfs-fuse-devbranches#1]
zfs-fuse have the code acl ,how to config zfs-fuse to support acl?

```
root@debian:/newzpool#mount
newzpool on /newzpool type fuse (rw,allow_other,default_permissions)

root@debian:/newzpool# echo "hello" >test.txt
root@debian:/newzpool# ls -l
total 1
-rw-r--r-- 1 root root 6 Sep  1 04:21 test.txt

root@debian:/newzpool# setfacl -m  u:miniadmin:rw- test.txt 
setfacl: test.txt: Operation not supported
```

i use debian is : 0.6.10
arch is: i386
zfs-fuse is : 0.6.9-1 
acl is: 2.2.49-4

**Comment by sehe** [comment]
You may need to enable the `acl` mount option in fstab, or by passing `-o` fuse mount options to zfs-fuse. You can also write them in zfsrc (default: /etc/zfs/zfsrc)

**Comment by lihui2090** [comment]
root@debian:/newzpool# zfs-fuse  -o acl
zfs-fuse: you need to specify mount options

**Comment by lihui2090** [comment]
i need destroy pool first?

**Comment by sehe** [comment]
of course not (you _might_ need to upgrade pool version but that's very very unlikely to relate to acl support)

**Comment by lihui2090** [comment]
i use debian is : 0.6.10  
arch is: i386
zfs-fuse is : 0.6.9-1 
acl is: 2.2.49-4

**Comment by sehe** [comment]
Please try to keep the comments tidy.

**Comment by lihui2090** [comment]
@sehe 
I am sorry.
I have edit the /etc/zfs/zfs/zfsrc  commented the fuse-mount-options = default_permissions
root#mount
newzpool on /newzpool type fuse (rw,allow_other)
newzpool/zdev on /newzpool/zdev type fuse (rw,allow_other)
root@debian:/newzpool/zdev# zfs-fuse -o acl
root@debian:/newzpool/zdev# setfacl -m u:miniadmin:rw- test.txt
setfacl: test.txt: Operation not supported

root#mount
newzpool on /newzpool type fuse (rw,allow_other)
newzpool/zdev on /newzpool/zdev type fuse (rw,allow_other)

this time the zfs-fuse is not work.

**Comment by sehe** [comment]
Ah I remember now, you need to enable xattr support instead (https://groups.google.com/forum/#!topic/zfs-fuse/uiWKDMZhQS8)

```
   -x --enable-xattr
       Enable support for extended attributes. Not generally recommended because it currently has a significant performance penalty for many
       small IOPS
```

Just tested it on ubuntu 14.04.3 LTS
